version: "3.8"

services:
  api:
    build: .
    container_name: jet-task-api-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app           # Permite hot reload
      - /app/node_modules 
      - ./data:/app/data 
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: jet-task-redis
    ports:
      - "6379:6379"
